### ISSUE TITLE
Download From Link || Doesn't Work 

### ISSUE THREAD

**Issue by sarhandev** [kleeja-official/kleeja#101]
When trying to use ( Download From Link ) the operation done and insert data in MySQL and put the file in uploads folder, but the file will be empty with 0 MB.

**Comment by abdumu** [comment]
fixed in latest commit, check it 😊

**Comment by sarhandev** [comment]
in this ? https://github.com/kleeja-official/kleeja/commit/d43b74050bb49bec704b020cbfdf793e223b2784
