### ISSUE TITLE
preg_replace e modifier error

### ISSUE THREAD

**Issue by ibrahimshatt** [kleeja-official/kleeja#103]
Kleeja error :

[ 8192:mysqli.php:424 ] 

preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead 

Visit Kleeja Website for more details.

**Comment by ibrahimshatt** [comment]
click to Refresh this page ...
Sorry , We encounter a MySQL error: Error In query

--[query]-------------------------- 
INSERT INTOf(`name` , `real_filename` , `size` , `time` , `folder` , `type` , `user` , `code_del` , `user_ip` , `id_form`) VALUES('1109-nws-ocr-l-drilling-02_60dce.jpg', '1109_nws_ocr-l-drilling-02.jpg', '80017', '1558291236', 'uploads', 'jpg', '-1', '55ec0c99499b3e094c925f578168a29556fdd3e7', '173.231.207.99', 'id')
---------------------------------

[1364 : Field 'last_down' doesn't have a default value] 


Script: Kleeja 
Kleeja Website

**Comment by abdumu** [comment]
@ibrahimshatt  open a new ticket for this issue
