### ISSUE TITLE
MySQL error: Error In query

### ISSUE THREAD

**Issue by ibrahimshatt** [kleeja-official/kleeja#104]
click to Refresh this page ...
Sorry , We encounter a MySQL error: Error In query

--[query]-------------------------- 
INSERT INTOf(`name` , `real_filename` , `size` , `time` , `folder` , `type` , `user` , `code_del` , `user_ip` , `id_form`) VALUES('1109-nws-ocr-l-drilling-02_a869b.jpg', '1109_nws_ocr-l-drilling-02.jpg', '80017', '1558293382', 'uploads', 'jpg', '-1', '8d42d9c8f0676899d0bee502a3df3f4c99e8a5a3', '173.231.207.99', 'id')
---------------------------------

[1364 : Field 'last_down' doesn't have a default value] 

Script: Kleeja 
Kleeja Website

**Comment by ibrahimshatt** [comment]
http://www.shatt.net/up/

**Comment by abdumu** [comment]
You upgraded from a previous version?

**Comment by ibrahimshatt** [comment]
Yes I did upgrade and i get many issues

**Comment by abdumu** [comment]
it's ok, that's because you upgraded from an old version. 

run this Query on your database (you could use phpMyAdmin for that): 

`ALTER TABLE `klj_files` CHANGE `last_down` `last_down` INT(11)  UNSIGNED  NOT NULL  DEFAULT '0';`

**Comment by ibrahimshatt** [comment]
same error : here what i did 

I open last down Columns and i changed to 


Name | Type | Collation | Attributes | Null | Default | Comments | Extra
last_down | int(11) |   |   | No | 0

and this error after i try to upload


click to Refresh this page ...
Sorry , We encounter a MySQL error: Error In query

--[query]-------------------------- 
INSERT INTOf(`name` , `real_filename` , `size` , `time` , `folder` , `type` , `user` , `code_del` , `user_ip` , `id_form`) VALUES('maersk.jpg', 'maersk.jpg', '1649754', '1558299618', 'uploads', 'jpg', '-1', '2c55977398c202734980baca5e846a368012917c', '173.231.207.99', 'id')
---------------------------------

[1364 : Field 'uploads' doesn't have a default value] 


Script: Kleeja 
Kleeja Website

**Comment by ibrahimshatt** [comment]
I change it to Value 0 and it's work 
uploads 0
Report 0
Thank You
