### ISSUE TITLE
Uploading problem 

### ISSUE THREAD

**Issue by DJboutit** [kleeja-official/kleeja#108]
I am try to upload a 50mb webm file it just goes back to the upload page when it should complete the upload.  I have been able to upload files up to 9mb it is just larger files that have this problem.  My host has set the upload size to 1gb so 50mb should not give any problems.  Any idea what could be wrong I installed the script 36hrs ago I have not been able to test it with this problem.

**Comment by abdumu** [comment]
Kleeja is just a helper script, it uses PHP settings. ask your hosting admin to solve this.

**Comment by DJboutit** [comment]
The admin of my host can not seem to figure out the problem.

**Comment by abdumu** [comment]
search google `php upload limit increase`
