### ISSUE TITLE
بعد التحديث للنسخة  3.1.1  تظهر صفحة بيضاء

### ISSUE THREAD

**Issue by teacher86** [kleeja-official/kleeja#110]
بعد التحديث ومحاولة تسجيل الدخول تظهر لى صفحة بيضاء

**Comment by abdumu** [comment]
احذف الكاش

**Comment by MitanOmar** [comment]
cache folder and plugins and uploads and styles , shoud to have read and write permission , can u check if they have permission or not
?

**Comment by teacher86** [comment]
قمت بتعديلها وبرضوا نفس المشكلة

**Comment by abdumu** [comment]
اضف التالي في الكونفق
`define('DEV_STAGE', true);`
 ثم اعد التجربة، اذا ظهر خطا انسخه هنا

**Comment by teacher86** [comment]
حطيت الكود فى نهاية الملف config.php وبرضوا بتظهرلى صفحة بيضاء بعد تسجيل الدخول

**Comment by abdumu** [comment]
Come to discord.

**Comment by teacher86** [comment]
مش فاهم ياريت تكتب عربى

**Comment by lamjed001** [comment]
> مش فاهم ياريت تكتب عربى

قال لك تعال ديسكورد : https://discord.gg/xaCZ4cQ

**Comment by teacher86** [comment]
تمام

> Come to discord.

ياريت تشوف الوقت الموجود فيه وتبلغنى
