### ISSUE TITLE
Error 404 after deleting Install Folder

### ISSUE THREAD

**Issue by s1ntaxerror** [kleeja-official/kleeja#112]
Hello. I installed Kleeja, everything worked fine. Then I deleted the install directory. But if I go on the website, kleeja everytime wants to go to /install/index.php and because I deleted that folder, I am getting a Error 404 message. Any ideas?

Thanks

**Comment by MitanOmar** [comment]
could u check config.php file ?

**Comment by s1ntaxerror** [comment]
> 
> 
> could u check config.php file ?

Config.php is filled with the right MySQL Data.

**Comment by MitanOmar** [comment]
still having this problem ??
if yes give me an URL of your website

**Comment by s1ntaxerror** [comment]
> 
> 
> still having this problem ??
> if yes give me an URL of your website

It is localhost but if you want I can upload it. But one question: In which format Kleeja is generating the image urls? like this? -> 127.0.0.1/imageid.php?=12345678, so a 8 digit or something different?

**Comment by MitanOmar** [comment]
Row ID in database (example.com/do.php?id=123)
File name (example.com/do.php?file=filename.pdf)
Direct (example.com/uploads/filename.pdf)
this is URLs examples , and if the website is in your local host i can not help so much , but try to check klj_config table in db , if the 'siteurl' is correct or not

**Comment by s1ntaxerror** [comment]
> 
> 
> Row ID in database (example.com/do.php?id=123)
> File name (example.com/do.php?file=filename.pdf)
> Direct (example.com/uploads/filename.pdf)
> this is URLs examples , and if the website is in your local host i can not help so much , but try to check klj_config table in db , if the 'siteurl' is correct or not

'siteurl' is correct but how are the Image ID's generated? Are they always only 3digit and which algorithmus is used to generate them?

**Comment by MitanOmar** [comment]
kleeja bring the ID from the database inserted ID , mysql make it unique , so kleeja is not generating the ID's , only bringing from mysql

**Comment by s1ntaxerror** [comment]
But how is MySQL creating that ID? And how much digits does that ID has?

**Comment by abdumu** [comment]
It's auto increment. It means 1+ the last number. If your website is new it will start from 1.

**Comment by dotcomUNDERGROUND** [comment]
Try disabling mod_rewrite.

That's the only way I can make the app work. 
Otherwise everything gives 404
