### ISSUE TITLE
مشكلة في تثبت الاضافات في الاصدار الاخير

### ISSUE THREAD

**Issue by HESHAMAREBI** [kleeja-official/kleeja#113]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - OS: [e.g. Linux]
 - PHP version: [e.g. 7.2]
 - MySQL version: [e.g. 8.0]
 - Version [e.g. 3.0]

**Additional context**

**Comment by HESHAMAREBI** [comment]
السلام عليكم
عند طلب تثبت أي  اضافة جديد من متجر الاضافات وعند تجربة جميع الاضافات لا يمكن تثبتها وتظهر الرسالة 
"خطأ , حاول مجدداً."



![image](https://user-images.githubusercontent.com/26428349/59266249-7d0bc200-8c47-11e9-8fef-971794ef6387.png)

**Comment by MitanOmar** [comment]
هل بأمكانك التأكد من مجلد الاضافات . هل لديه تصريح الكتابة ام لا ؟
