### ISSUE TITLE
مساعد في تحميل عن طريق رابط

### ISSUE THREAD

**Issue by LIONHAERT** [kleeja-official/kleeja#116]
مرحبا اخواني هل تم إلغاء رفع ملفات عن طريق رابط ولماذا

**Comment by abdumu** [comment]
طبقا لاحصائياتنا لا يستخدمها الا نسبة بسيطة جدا، بالاضافة لكونها تحتاج اصلاحات لا داعي لها.

**Comment by LIONHAERT** [comment]
انا اريد سحب الملفات عن طريق روابط ارجو الحل
