### ISSUE TITLE
مشكلة بعد الإنشاء

### ISSUE THREAD

**Issue by mix2vb** [kleeja-official/kleeja#117]
مشكلة بعد الإنتهاء من إنشاء البرنامج يقوم بتحويلي إلى 
ملف 
install 
وانا قمت بحذفه 
يرجى ملاحظة أنه تم الإنتهاء من الإعداد بنجاح ولا يوجد أي أخطاء ما هي المشكلة حتى أقوم بحلها في أسرع وقت

**Comment by MitanOmar** [comment]
ما هو نوع قاعدة البيانات ؟
Sqlite ام mysql ??

**Comment by mix2vb** [comment]
انا استخدم xampp

**Comment by MitanOmar** [comment]
افتح الملف التالي 
Includes/common.php
و استبدل محتوياته بمحتويات هذا الملف .
https://raw.githubusercontent.com/kleeja-official/kleeja/master/includes/common.php
جميع المشاكل المتعلقة بتوجيه المستخدم لصفحة التثبيت تم حلها . وهذه كانت آخرها

**Comment by mix2vb** [comment]
مفيش جديد

**Comment by MitanOmar** [comment]
هل تحققت من معلومات الاتصال بقاعدة البيانات في ملف
Config.php هل كل شيء على ما يرام هناك ؟

**Comment by mix2vb** [comment]
المشكلة مش في ملف ال config لإن  الموقع يحولك إلى ملف install وليس إعطاء مشاكل بقاعدة البيانات ... وللتأكيد ليس هناك أي مشكلة في ملف الكونفج المتصل بقاعة بالبيانات

**Comment by MitanOmar** [comment]
تعال هنا و كلمني خاص
https://discord.gg/xaCZ4cQ

**Comment by asbahi-m** [comment]
نفس الإشكالية عندي، وأنا أستخدم  برنامج
AppServer
PHP Version 7.1.1
MySQL Version 5.7.17
الرجاء توجيهنا لحل هذه المشكلة، ومعالجتها في الإصدارات القادمة

**Comment by G88808G** [comment]
السلام عليكم 
لدي نفس المشكلة مع سيرفر xampp
هل يوجد حل

**Comment by MitanOmar** [comment]
هل بأمكانكم وضع روابط مواقعكم .
لاننا مازلنا نتحقق هذه المشكلة

**Comment by mix2vb** [comment]
الموقع هو http://shortocash.com/myfile

**Comment by MitanOmar** [comment]
fixed with https://github.com/kleeja-official/kleeja/commit/16dab0e04a13da02ff73c692ab6561c1a41817be

**Comment by asbahi-m** [comment]
شكراً شكراً جزيلا..
فعلاً تم حل المشكلة بعد تحديث البروجيكت وتنزيل الملفات المعدلة.
