### ISSUE TITLE
استفسار بخصوص نظام عضوية المنتديات

### ISSUE THREAD

**Issue by asbahi-m** [kleeja-official/kleeja#119]
فضلاً، أريد الاستفسار عن نظام عضوية المنتديات، هذا الخيار لم يعد متاحاً في الإصدار الحديث.

هل ألغيتم نظام العضويات أم ماذا؟

وشكراً

**Comment by MitanOmar** [comment]
افتح لوحة التحكم ومن قسم الاضافات ستجد متجر كليجا 
ستجد فيها تطبيقين لنظام عضوية المنتديات .وكل منها لها لوحة تحكم خاصة بها . ادخل المعلومات المناسبة و استمتع به

**Comment by MitanOmar** [comment]
VBulletin Integration , phpBB Integration
this is the plugins name

**Comment by asbahi-m** [comment]
أحسن الله إليك أخانا.
ثبت الإضافة وفعلتها، وعند الدخول يظهر لي هذا الخطأ بخصوص الترميز في قاعدة البيانات:
Sorry , We encountered a MySQL error: Error In query

--[query]--------------------------
SELECT s FROM u WHERE username='الإدارة' AND u != '8'
---------------------------------

[1267 : Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '=']

**Comment by MitanOmar** [comment]
come here https://discord.gg/xaCZ4cQ
