### ISSUE TITLE
how to create a foder

### ISSUE THREAD

**Issue by luciomor** [kleeja-official/kleeja#120]
how to create folders and send files to each folder separately?

**Comment by abdumu** [comment]
If you read carefully the settings you will find: 

> Folder name for uploaded files (you can use {year}, {month}, {day} ,{week} ,{username})


so, in folder name you can use `/uploads/{username}/{year}` -> which will be /uploads/luciomor/2019

**Comment by luciomor** [comment]
ok, plus I would like to send a link to a person from a folder containing specific files just for that person. Create multiple folders besides "YOUR FOLDER"
