### ISSUE TITLE
Url Uploads Disabled And Setting Removed From Admin Panel.  

### ISSUE THREAD

**Issue by DJboutit** [kleeja-official/kleeja#121]
I just updated to the newest version of Kleeja and url uploads has been disabled I went into the admin panel to look to for the setting to turn back it back on and I can not find it.  I think url uploads has been accidentally removed just letting you know.

**Comment by abdumu** [comment]
@DJboutit it was deleted since only less than 1% of users use it. If u want such feature i suggest u use specialized leech script

**Comment by agnnus** [comment]
please
i want this feature please make it again please

**Comment by DJboutit** [comment]
If you want this feature you have to down grade to version 3.0.2 to do this you have to delete all the files and then reinstall it. Installing the older files over a newer version does not downgrade.

**Comment by agnnus** [comment]
thank you
