### ISSUE TITLE
plugins don't installing how can be fix it this probleme

### ISSUE THREAD

**Issue by agnnus** [kleeja-official/kleeja#122]
hello
wen i try to install any plugins its show me error try again how can i fix this probleme please

**Comment by abdumu** [comment]
copy and paste the error here.

**Comment by agnnus** [comment]
[url=https://up.top4top.net/][img]https://1.top4top.net/p_1295q8uvl1.png[/img][/url]

**Comment by agnnus** [comment]
![FireShot Capture 002 - Control Panel - File4Up - مركزك لتحميل الصور - www file4up ml](https://user-images.githubusercontent.com/47098517/61555093-71859500-aa56-11e9-84c3-5b9ff3657b47.png)

**Comment by abdumu** [comment]
Do you still have this issue ?

**Comment by agnnus** [comment]
yes i still have this probleme

**Comment by abdumu** [comment]
come to discord: https://discord.gg/8E69p2

**Comment by MitanOmar** [comment]
check here https://github.com/kleeja-official/kleeja/issues/142
