### ISSUE TITLE
مشكلة قاعدة البيانات كليجا

### ISSUE THREAD

**Issue by basem1441** [kleeja-official/kleeja#123]
http://up.n17n.net/

مشكلة عند رفع اي ملف 

Sorry , We encountered a MySQL error: Error In query

--[query]-------------------------- 
INSERT INTO f (`name` , `real_filename` , `size` , `time` , `folder` , `type` , `user` , `code_del` , `user_ip` , `id_form`) VALUES('13747159931.gif', '13747159931.gif', '214254', '1564603585', '7', 'gif', '-1', 'd00765c31697ac273e35d1e08c84560e504d5364', '95.219.223.187', 'filename')
---------------------------------

[1364 : Field 'last_down' doesn't have a default value] 

--------------------------------------

المشكللة الثانية 

جميع مقاطع mp3 و mp4 ما تشتغل

كان شغال على الاصدار القديم 

و رقيته نسخه نسخه حتى وصلت للاصدار الاخير

**Comment by basem1441** [comment]
تم حل مشكلة قاعدة البيانات 

الحل هو 

نبحث عن 
`CREATE TABLE `klj_files` (
  `id` int(10) NOT NULL,
  `last_down` int(11) NOT NULL,
  `name` varchar(300) COLLATE utf8_bin NOT NULL,
  `real_filename` varchar(350) COLLATE utf8_bin NOT NULL,
  `size` bigint(20) NOT NULL DEFAULT 0,
  `uploads` int(10) NOT NULL,
  `time` int(11) NOT NULL,
  `type` varchar(100) COLLATE utf8_bin NOT NULL,
  `folder` varchar(100) COLLATE utf8_bin NOT NULL,
  `report` int(10) NOT NULL,
  `user` int(10) NOT NULL DEFAULT -1,
  `code_del` varchar(150) COLLATE utf8_bin NOT NULL,
  `user_ip` varchar(250) COLLATE utf8_bin NOT NULL,
  `id_form` varchar(100) COLLATE utf8_bin NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
`



و نستبدلها 

`
CREATE TABLE `klj_files` (
  `id` int(11) UNSIGNED NOT NULL,
  `last_down` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `name` varchar(300) COLLATE utf8_bin NOT NULL,
  `real_filename` varchar(350) COLLATE utf8_bin NOT NULL,
  `size` bigint(20) UNSIGNED NOT NULL DEFAULT 0,
  `uploads` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `time` int(11) UNSIGNED NOT NULL,
  `type` varchar(20) COLLATE utf8_bin NOT NULL,
  `folder` varchar(100) COLLATE utf8_bin NOT NULL,
  `report` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `user` int(11) NOT NULL DEFAULT -1,
  `code_del` varchar(150) COLLATE utf8_bin NOT NULL,
  `user_ip` varchar(250) COLLATE utf8_bin NOT NULL,
  `id_form` varchar(100) COLLATE utf8_bin NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
`

**Comment by abdumu** [comment]
@basem1441 المشكلة الأخيرة هل لازلت لديك ؟

**Comment by basem1441** [comment]
نعم

عند استرجاع الباك اب 
مافي ولا ملف
mp4 أو mp3

يمكن المشكله من الباك اب

لاكن إذا حملت من جديد عادي يتحمل معي 

اذا في حل للاسترجاع
او حذف جميع الملفات الي تحمل نفس الصيغه من القاعدة
