### ISSUE TITLE
مشكلة إضافة الأعضاء وتسجيل عضوية جديدة

### ISSUE THREAD

**Issue by asbahi-m** [kleeja-official/kleeja#125]
إخوتي الأفاضل كيف يمكنني إضافة أعضاء من لوحة التحكم، لم أجد أي خيار لإضافة أعضاء جدد أو مسؤولين.

وكذلك يوجد مشكلة في صفحة تسجيل عضوية جديدة

عند الانتقال لتسجيل عضوية جديدة يظهر الخطأ التالي:
خطأ بالتوجه.. 
رجوع للخلف

شاكرين لكم حسن تعاونكم وتعاملكم.

**Comment by MitanOmar** [comment]
لاضافة عضو جديد تحتاج للذهاب الى الاعضاء و المجموعات و ستجد اسفل القائمة خيار عضو جديد
ولكن بما انك تستخدم نظام الربط بالمنتدى . فأن عملية اضافة عضو جديد يجب ان تكون من المنتدى . و بالنسبة للخطأ في صفحة تسجيل الدخول . عند استخدام احدث نسخة من الاضافة ستجد خيار في لوحة التحكم لاضافة رابط التسجيل . ويجب ان يكون رابط تسجيل المنتدى

**Comment by asbahi-m** [comment]
أستاذ ميتان أولاً شكراً على سرعة استجابتك.

أنا أستخدم حالياً نظام العضويات العادي وليس نظام الربط بالمنتدى.
وأيضاً لا توجد أيقونة إضافة عضو في صفحة الأعضاء والمجموعات.

**Comment by MitanOmar** [comment]
بعد ان تفتح صفحة الاعضاء و المجموعات . ستجدها في القائمة الجانبية . وليس ضمن الصفحة

**Comment by asbahi-m** [comment]
![image](https://user-images.githubusercontent.com/40779102/63231313-7e96cf00-c222-11e9-95b1-eeca7d323113.png)
لم أجدها حبيبنا.

**Comment by asbahi-m** [comment]
تم حل المشكلة عبر تغيير قيمة
user_system = 1
في جدول klj_config

كل الشكر والتقدير للأستاذ ميتان
