### ISSUE TITLE
لا يقبل التحديث التلقائي

### ISSUE THREAD

**Issue by aljailane** [kleeja-official/kleeja#126]
<img src="https://files.aljup.com/uploads/c30249bdb53b1.png" border="0" alt="https://files.aljup.com/uploads/c30249bdb53b1.png" />

**Comment by MitanOmar** [comment]
`define('DEV_STAGE', true);`
اضف هذه الى ملف الكونفيج و حاول التحديث مرة اخرى

**Comment by aljailane** [comment]
اضفت الكود وللاسف ظهر كما تشاهد بالصورة
<img src="https://files.aljup.com/uploads/09aea6bdf6951.png" border="0" alt="https://files.aljup.com/uploads/09aea6bdf6951.png" />

**Comment by MitanOmar** [comment]
تحقق من صلاحية مجلد includes
اعطها صلاحية القراءة و الكتابة

**Comment by MitanOmar** [comment]
if you still have this problem , reopen this issues again
