### ISSUE TITLE
Plugins don't appear in installed plugin after installation

### ISSUE THREAD

**Issue by shiraliali** [kleeja-official/kleeja#128]
**Plugins don't appear in installed plugin after installation**
Plugins will be downloaded successfully and they appear in plugins folder at the server, but don't appear any of them at plugin installed in dashboard ! Im using php 7.2 
Please help me
Best regards

**Comment by shiraliali** [comment]
** I think there is a serious problem with the caching and cookies system **

Installing plugins and other part of admin have the same problem. After installing a plugin you need to manually refresh the page to see what plugins are added if you can't see the added plugins to enable it or whatever.

 Also when logout & login to dashboard, Statistics dose not get any change while the page is not refreshed manually!

In some actions like enabling plugins i faced with ** your session expired ** error after logout and login again there is need to login twice! it's really bad.

It's definitely related to cache and cookies.
Please fix it in future releases.

Best regards

**Comment by abdumu** [comment]
> Statistics dose not get any change while the page is not refreshed manually!
yes, we do not use real time refresh (ajax) for stats, only we use it for messages + reports counter. so we might add it in the future

> your session expired
this only appears if you leave page for so long, and as a security measure we log you out for admin panel. 

> After installing a plugin you need to manually refresh the page to see what plugins are added if you can't see the added plugins to enable it or whatever.
@MitanOmar are you aware of this?

**Comment by MitanOmar** [comment]
`After installing a plugin you need to manually refresh the page to see what plugins are added if you can't see the added plugins to enable it or whatever.`
i will be so happy if you make a pull request to fix this error , since it's not a bug .
@shiraliali
