### ISSUE TITLE
Problem in displaying image when using another ftp server

### ISSUE THREAD

**Issue by shiraliali** [kleeja-official/kleeja#129]
**Images don't displayed when using another ftp server for storage**
When using ftp plugin for connecting to another server as storage all images files can not displayed  and just a white screen shows up .

It could be great if you provide documentation to developers cause no one cant figure it what main developer done in it's product :smile: 
Fix this issue.
Thanks.

**Comment by shiraliali** [comment]
I understand that **Noting didn't transfered to ftp server**
File names will created but with 0 byte sizes !

**Comment by shiraliali** [comment]
It was my host . Solved

**Comment by shiraliali** [comment]
I used a download server, My dl server have an ip to put it in host field
Tried to connect another server ( it wasn't dl server just a regular site server ) that instead of an ip i be able to put ftp.mydomain.com in host field and it works like a charm 

But in download server with ip connection will be ok and `uploads` folder will created and file will created but with 0 byte size ( htaccess and other files have 0  byte size ) 

Please review it.

**Comment by abdumu** [comment]
I see that you solved your first problem.
the second problem is mostly due your plugin ftp settings, adjust the settings until the problem resolve.

(Please use the discord support channel for support questions, and only use issues tracker for programmatic bugs)
