### ISSUE TITLE
MySQL error: Error In query

### ISSUE THREAD

**Issue by W3bCrak3r** [kleeja-official/kleeja#130]
Hi there,

Just tried to delete a photo from the control panel and getting the error below

Sorry , We encountered a MySQL error: Error In query
--[query]--------------------------
UPDATE s SET sizes=sizes-34903, imgs=imgs-1
---------------------------------
[1690 : BIGINT UNSIGNED value is out of range in '(`database_up`.`klj_stats`.`imgs` - 1)']
---------------------------------

Notes; Kleeja updated to the latest version

Please advice,

**Comment by abdumu** [comment]
did you try to resync from maintenance page

**Comment by W3bCrak3r** [comment]
> did you try to resync from maintenance page

Did that already after upgrading.

**Comment by abdumu** [comment]
upgrade to latest version and make sure to check if your database is updated too from example.com/kleeja/install
