### ISSUE TITLE
Issue with vBulletin integeration

### ISSUE THREAD

**Issue by W3bCrak3r** [kleeja-official/kleeja#131]
Upgraded to the latest version of kleeja and did a vbulletin integration successfully but getting SQL error when login with arabic usernames only

Sorry , We encountered a MySQL error: Error In query

--[query]--------------------------
SELECT s FROM u WHERE username='علي علي' AND u != '8'
---------------------------------

[1267 : Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '=']

**Comment by W3bCrak3r** [comment]
Also tried to change the Database char encoding in the VBulletin Intergration options to these values with no luck

latin1_swedish_ci
utf8

**Comment by abdumu** [comment]
You should convert vb database to utf8. We dropped support of any other encoding.

**Comment by W3bCrak3r** [comment]
> You should convert vb database to utf8. We dropped support of any other encoding.

Thank you for replying, anyway UTF-8 is better.
