### ISSUE TITLE
مشكلة بالتحديث التلقائي

### ISSUE THREAD

**Issue by aljailane** [kleeja-official/kleeja#133]
انت تستخدم نسخة قديمة من كليجا، قم بالترقية فوراً، نسختك الحالية هي 3.1.4 والنسخة الجديدة هي 3.1.5 .

1 جلب حزمة آخر نسخة من كليجا...
2 إنشاء وعاء نسخة إحتياطية وفك حزمة آخر نسخة ...
3 الترقية للنسخة الجديدة (تحديث الملفات وقاعدة البيانات) ...
عملية التحديث فشلت![failed files: ../CHANGELOG.md]

**Comment by MitanOmar** [comment]
تحقق من صلاحيات الملف اذا كان قابل للقراءة و الكتابه ثم اعد محاولة التحديث . اذا لم يفلح هذا، قم بحذف الملف من الإستضافة و اعد محاولة التحديث

**Comment by aljailane** [comment]
شكرا جزيلا لك اخي الكريم فعلا المشكلة من الصلاحيات اضطريه اصرح للكل 777 وزبط

انت تستخدم نسخة قديمة من كليجا، قم بالترقية فوراً، نسختك الحالية هي 3.1.4 والنسخة الجديدة هي 3.1.5 .

1 جلب حزمة آخر نسخة من كليجا...
2 إنشاء وعاء نسخة إحتياطية وفك حزمة آخر نسخة ...
3 الترقية للنسخة الجديدة (تحديث الملفات وقاعدة البيانات) ...
تم تحديث كليجا إلى النسخة `3.1.5` بنجاح...

**Comment by MitanOmar** [comment]
مبروك
