### ISSUE TITLE
لا استطيع تسجيل الدخول الى لوحة التحكم

### ISSUE THREAD

**Issue by HamadaRh** [kleeja-official/kleeja#134]
مرحباً
لا استطيع تسجيل الدخول الى لوحة التحكم
بالرغم من تواجدى وتسجيل الدخول الطبيعى بمركز الرفع ولكن عند الدخول الى لوحة التحكم وكتابة كلمة المرور وتسجيل الدخول لايتم ويتم اعادة طلب كلمة المرور مرة اخرى وكأن شئ لم يتم ادخال وهكذا
https://i.vgy.me/VoYOLh.png
ايضا لايفيد استخدام FORCE_COOKIES بملف الكونفيج

ايضا ،، توجد لدى مشكلة باكواد الامان والكابتشا 
لابد من تعطيلها من خلال الكونفيج حتى استطيع تسجيل الدخول الى مركز الرفع
هل توجد طريقة اخرى لحلها او لتفعيل اكواد الامان

**Comment by sarhandev** [comment]
الرجاء إرسال رابط الموقع، وهل قمت بإضافة https للرابط ؟

بإمكانك الإنضام للديسكورد للتواصل بشكل اسرع
https://discord.gg/vYJwPVq

**Comment by MitanOmar** [comment]
@HamadaRh 
if you still having this problem, check your PHP ini file ,
try to change your setting to be like this:
``` session.use_cookies = 1
    session.lazy_write = 1
    session.cache_expire = 0
    session.cache_limiter = ''
    session.use_only_cookies = 1
