### ISSUE TITLE
السحب الالي للصور

### ISSUE THREAD

**Issue by leech24** [kleeja-official/kleeja#135]
السحب الالي للصور به مشكله

**Comment by MitanOmar** [comment]
@leech24 وضح المشكلة اكثر من فضلك

**Comment by leech24** [comment]
الرفع من رابط
لايعمل نهائيا اضطررت للرجوع لاصدار القديم

**Comment by MitanOmar** [comment]
@leech24 ميزة الرفع من الرابط تمت ازالتها لوجود بعض المشاكل . قد يتم ارجاعها لاحقا على هيئة إضافة
