### ISSUE TITLE
مشكلة الدخول بعضوية ادمن المنتدى بعد الترقية

### ISSUE THREAD

**Issue by saiffon** [kleeja-official/kleeja#136]
السلام عليكم
بعد الترقية للنسخة الاخيرة لم اعد استطع الدخول الى لوحة التحكم لابعضوية ادمن المنتدى ولابعضوية ادمن كليجا.
Error ... cannot login!
* المنتدى في بي جيل خامس

شكرا مسبقا

**Comment by MitanOmar** [comment]
اذا لم يكن ترميز المنتدي هو utf8
فيفضل تحويل الترميز.
اما بالنسبة لعضوية المدير في كليجا . فقم بتعطيل التطبيقات وحاول الدخول

**Comment by saiffon** [comment]
ترميز المنتدى تم تحويله الى uft8mb4

هل ادخل بعضوية المنتدى ام بعضوية الادمن قبل الربط مع المنتدى؟

كيف يتم تعطيل التطبيقات؟
شكرا

**Comment by MitanOmar** [comment]
قبل الربط بإمكانك الدخول الى المنتدى بعضوية ادمن كليجا .
ولتعطيل التطبيقات : افتح ملف الكونفيج ثم اضف التالي الى نهاية الملف
`define('STOP_PLUGINS', true);`
وبعدها يمكنك الدخول بعضوية كليجا

**Comment by saiffon** [comment]
شكراً لك
بالنسبة لترميز قاعدة المنتدى ليس مشكلة؟

**Comment by MitanOmar** [comment]
فعل الإضافات في كليجا و حاول الدخول عن طريق حساب في المنتدى . اذا دخل فمعناها كل شيء على ما يرام

**Comment by saiffon** [comment]
للاسف لم ننجح

تظهر هاته الإشارة فوق خانة الدخول
Login
Login + Members Only

**Comment by abdumu** [comment]
مرحباً
- قم بتفعيل اضافة الدخول عن طريق الفي بي من الاضافات
- تاكد ان الربط صحيح من خلال اعدادات الاضافة من زر التشييك 

قم بالتوجه لقناة الديسكورد لدعم كليجا عند وجود مشاكل اخرى

**Comment by saiffon** [comment]
اين اجد القناة؟
حالياً قمت باستعادة نسخة ماقبل الترقية.جربت رفع صورة ظهر لي هذا الخطأ وهو في الاصل الذي جعلني أرقي

Instructions
: Error: cannot upload file "IMG-20191210-WA0009.jpg" for UNKNOWN reason!
