### ISSUE TITLE
Still no remote uploading 

### ISSUE THREAD

**Issue by DJboutit** [kleeja-official/kleeja#137]
Still no remote uploading remote uploading is 90% of what I use this script for to remote upload images.  Please bring back remote uploading I am still using version 3.0.2 untill this is brought back.

**Comment by abdumu** [comment]
Please don't add non-issues here. Use Discord channel for these matters.

**Comment by abdumu** [comment]
Please don't add non-issues here. Use Discord channel for these matters.
