### ISSUE TITLE
erorr download fil apk in google chorome androide

### ISSUE THREAD

**Issue by amiirhk** [kleeja-official/kleeja#138]
**Describe the bug**

**To Reproduce**
1. Go to 'http://dl.novelman.ir/ups/do.php?id=164'
2. Click on download in google chorome android

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - OS: [e.g. Linux]
 - PHP version: [e.g. 7.2]
 - MySQL version: [e.g. 8.0]
 - Version [e.g. 3.0]

**Additional context**

**Comment by amiirhk** [comment]
Html file is downloaded instead of file

**Comment by abdumu** [comment]
Are using latest kleeja version?

**Comment by ayhmhost** [comment]
[شات صبايا بغداد](https://www.iraq-5.com)

**Comment by amiirhk** [comment]
> آیا از آخرین نسخه kleeja استفاده می کنید؟



> Are using latest kleeja version?

Yes I'm using the latest version

**Comment by amiirhk** [comment]
https://picax.ir/upload/yqsl_rec_0012.mp4

**Comment by amiirhk** [comment]
![photo_2020-01-06_16-47-11](https://user-images.githubusercontent.com/44585082/71820400-33cc0580-30a4-11ea-9305-66505f7734b3.jpg)




Apk files are downloaded instead of web page files

**Comment by MitanOmar** [comment]
after some update in Google chrome, the file is downloaded without any problems
