### ISSUE TITLE
كليجا

### ISSUE THREAD

**Issue by tareknabawy** [kleeja-official/kleeja#140]
السلام عليكم
انا مشكله بالموقع اريد حل لها المشكله عند تحميل ملف من الموقع بصيغه apk يجري التحميل ولاكن الملف تالف

**Comment by abdumu** [comment]
هناك مشكلة بنفس الخطأ مفتوحة حالياً :
#138 

تابع مستجداتها وتأكد ان لديك اخر نسخة من كليجا.

ساغلق هذه التذكرة للتكرار
