### ISSUE TITLE
اضافة adf.ly

### ISSUE THREAD

**Issue by leech24** [kleeja-official/kleeja#141]
**Describe the bug**
هل سيتم تطوير اضافلا اد فلاي
اذا كان ممكن ارجو اضافه المواقع الاخري لاضافه

**To Reproduce**
بعد رفع الفايلات بسبب الاضافه
تاتي صفحه بيضاء

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - freebsd
 - php 7.2
 - MySQL version: [e.g. 8.0]
 - Version [e.g. 3.0]

**Additional context**
klj_adfly اسم الاضافه

كانت تعمل بشكل جيد مع الاصدار 3.0

**Comment by MitanOmar** [comment]
now you can see that there is an update for the plugin,
update it, and it ill work, thanks for reporting!
