### ISSUE TITLE
مشكلة في تثبت الأضافات

### ISSUE THREAD

**Issue by LIONHAERT** [kleeja-official/kleeja#142]
مرحبا يوجد مشكلة عند تثبت الأضافات 
خطأ , حاول مجدداً
ما هو الحل

**Comment by mjawshy** [comment]
هل عرفت لها حل

**Comment by LIONHAERT** [comment]
لا والله صديقي

**Comment by mjawshy** [comment]
الله المستعان

**Comment by LIONHAERT** [comment]
اخي لا احد يستجيب من الدعم الفني

**Comment by MitanOmar** [comment]
there will be a plugin for this problem, we are working on it

**Comment by mjawshy** [comment]
اشكرك وننظر منكم الحل

**Comment by MitanOmar** [comment]
https://github.com/kleeja-official/alternative_store/releases/download/1.0/alternative_store.zip
by clicking this link, there will be a plugin called `alternative_store` will be downloaded,
upload this plugin to your kleeja app, and enjoy using the store
please don't forget to send my the feedback about how it was working with you.
Kleeja Team

**Comment by MitanOmar** [comment]
hope it's fixed
