### ISSUE TITLE
مشكلة في تحديث نسخة كليجا

### ISSUE THREAD

**Issue by Akadoorah** [kleeja-official/kleeja#143]
السلام عليكم

أنا من أوائل الأشخاص الذين استخدموا برمجية كليجا في رفع الملفات والصور، وأظن أن النسخة التي كانت لدي هي الأولى، حاليًا بعد ترك الساحة لفترة طويلة قررت العودة واستخدام النسخة الجديدة وتحديث النسخة القديمة، حالما قمت بذلك تطلب الأمر مني نسخة PHP7.1 وأعلى
وقمت بذلك بالفعل، حاليًا تواجهني مشكلة وهي أنني حينما أضغط على تحديث النسخة تظهر لي صفحة بيضاء فقط بها نصف الشعار، مرفق صورة للتوضيح:
https://i.imgur.com/bYAixVW.png

حاولت إيقاف الإضافات وما شابه من الكونفنج، لكن لم ينفع
![00](https://user-images.githubusercontent.com/62778427/77809880-c62be600-70a2-11ea-916b-e099a00c8e4d.png)

أتمنى مساعدتي لتطوير النسخة لاستخدامها، إذ أني أستخدم النسخة لرفع الصور فقط.

تحياتي للجميع

**Comment by Akadoorah** [comment]
ما زلت في الانتظار

**Comment by abdumu** [comment]
قم باستخدام متصفح اخر 
احذف ملف كونفق واعد التثبيت 
قم بقراءة ملف الاخطاء على الخادم ومعرفة سبب الخطأ
او قم بتفعيل عرض اخطاء بي اتش بي من الخادم ليظهر الخطأ الذي اوقف عملية التثبيت

**Comment by mjawshy** [comment]
كم النسخه السابقه

**Comment by Akadoorah** [comment]
النسخة الأولى، عمومًا قمت بتثبيت النسخة القديمة مرة أخرى وعاد كل شيء في مكانه.

**Comment by MitanOmar** [comment]
we fixed this problem, the fix will be available in the next version
