### ISSUE TITLE
اوامر قاعدة البيانات سكربت كليجا

### ISSUE THREAD

**Issue by basem1441** [kleeja-official/kleeja#146]
في امر اقدر احذف جميع الملفات المرفوعه لصيغة معينة

مثلا حذف جميع ملفات mp3 

بدل ما احددها صفحه صفحه 

تاخذ وقت طويل جدا جدا

**Comment by MitanOmar** [comment]
سأحاول ان اضيفها كميزة في النسخة القادمة. حليا حتى و ان اعطيتك جملة الاستعلام لقاعدة البيانات . ستبقى الملفات موجودة في مجلد التحميلات . لذلك يجب ان يكون هناك اوامر بي اتش بي ايضا حتى تتخلص منها نهائيا .

**Comment by basem1441** [comment]
والله ياليت 
لان عندي ملفات mp3 
اكثر من نص مليون ملف 

لي كم شهر وانا احذف فيها ما خلصت
