### ISSUE TITLE
Instructions : it's anti-flood system ...

### ISSUE THREAD

**Issue by kvolcano** [kleeja-official/kleeja#148]
Instructions : it's anti-flood system ...
 This message appears when uploading a file that does not exceed 37MB

**Comment by MitanOmar** [comment]
this case is coming when you are trying to upload the same file more then one time,
and after you see this message, you can upload the file again,
anyway it's just checking the file name, if you want to not see this message and you have tow file and you want to uplad the both, try to change the file name, and everything will be ok.
