### ISSUE TITLE
The private upload center for my site is not working, please help me fix it

### ISSUE THREAD

**Issue by ahnancom** [kleeja-official/kleeja#149]
http://www.alhnan.com/up/

click to Refresh this page ...
Sorry , There is an error in mysql , error : we can not connect to the server ...
[1045 : Access denied for user hidden@localhost (using password: YES)]
Script: Kleeja
Kleeja Website

**Comment by MitanOmar** [comment]
check mysql username and password, it's not correct

**Comment by ahnancom** [comment]
How to check and show me a blank page
Help me with the steps

**Comment by MitanOmar** [comment]
if you know your password, go to `config.php` file, and update the details of database connection

**Comment by MitanOmar** [comment]
this may help you.
https://github.com/kleeja-official/kleeja/wiki/config.php-file

**Comment by ahnancom** [comment]
Thank you, work on the site
Like

http://www.alhnan.com/vb/
http://www.alhnan.com/up/
