### ISSUE TITLE
I have issue upgrading kleeja script

### ISSUE THREAD

**Issue by NiGh10GaLe** [kleeja-official/kleeja#150]
I got this error after upgrading.
Fatal error: Uncaught Error: Call to undefined function big_error() in /home/akamelco/public_html/up/includes/common.php:139 Stack trace: #0 /home/akamelco/public_html/up/index.php(27): require_once() #1 {main} thrown in /home/akamelco/public_html/up/includes/common.php on line 139

**Comment by MitanOmar** [comment]
@NiGh10GaLe there is an error of starting the sessions,
check your `php.ini` file and change some variables to be like this example:
* session.use_cookies = 1
* session.lazy_write = 1
* session.cache_expire = 0
* session.cache_limiter =
* session.use_only_cookies = 1
