### ISSUE TITLE
add persain language

### ISSUE THREAD

**Issue by dailymobile** [kleeja-official/kleeja#151]
.
please add persain language again

**Comment by mahdim8m** [comment]
You can buy languages $10 For each language ($5 For the page main and $5 For the page admin)

**Comment by lamjed001** [comment]
I already have it but i don't translate many texts
when i finish it i will make pull request and i hope @MitanOmar will accept it :)

**Comment by munjoob** [comment]
try kleeja.org

**Comment by MitanOmar** [comment]
الموقع المعتمد الوحيد الذي نضمنه هو kleeja.net
تنزيل برمجية كليجا من موقع غير موقعنا، يخلي مسؤليتنا من الشفرة البرمجية اذا كانت تحوي اكواد خبيثة او عمليات جمع بيانات وانتهاك خصوصية

**Comment by mahdim8m** [comment]
ميتان عمر اذا كنت انتهيت من عملك راسلني على ديسكورد اناMustafapro راسلني بحساب mahdim8m

**Comment by MitanOmar** [comment]
added
