### ISSUE TITLE
طلب إضافة: معلومات تحميل الملف أثناء الرفع

### ISSUE THREAD

**Issue by asbahi-m** [kleeja-official/kleeja#159]
**هذا طلب تطويري لفريق كليجا الرائع.

نتمنى إضافة معلومات ونسب ملف التحميل أسفل كل تحميل وذلك عند الرفع.
حجم التحميل الإجمالي / حجم التحميل المتبقي / معدل النقل / الوقت المقدر لانتهاء التحميل / الوقت المتبقي ... إلخ

وكل الشكر والتقدير لكم.**
![image](https://user-images.githubusercontent.com/40779102/87623019-118b0280-c72d-11ea-98c8-8d0946462eea.png)

**Comment by MitanOmar** [comment]
هذه الاشياء ستدرجها في الاضدار القادم الذي نعمل عليه
https://youtu.be/OX_fg7UkeSI
هذه احد الامثلة و نعمل على تطويره.
نحتاج فقط بعض الوقت لانهائه
