### ISSUE TITLE
SSL problem

### ISSUE THREAD

**Issue by furkngzl** [kleeja-official/kleeja#163]
I bought ssl from hosting and uploaded it to the site, but the kleeja script does not accept the https protocol. The site crashes. What is the reason for this? How can we fix it? Can we help?
![Adsız](https://user-images.githubusercontent.com/72542289/95423639-133e1e00-094a-11eb-86ae-81bc05efb55e.png)

**Comment by MitanOmar** [comment]
make sure that u change the URL in the config table in the database, or go to the setting and change the link to https protocol, then upload the certeficate to the host
