### ISSUE TITLE
Kleeja Upload files to server1 or server2

### ISSUE THREAD

**Issue by Wenbyn** [kleeja-official/kleeja#164]
Helo,

I have been using your script for many years.  I'm wondering if it's possible when someone uploading file to my main domain (for example: www.maindomain.com) to upload the file to my sub domain (for example: www.server1.maindomain/do.php?filename=7c11eb992bzb1.pdf)

I am asking you this question because of the HD space on my server. I want to create a sub domain and all members who upload files via my main domain to place that file to another server where I have more space on HD.

I'm waiting for your reply. Thank you so much for this beautiful script, I have been using it for many years.

Regards.

**Comment by Wenbyn** [comment]
No one answers anything?
It would be good to have paid support.

**Comment by Wenbyn** [comment]
Please let me know, I will pay you for support.

**Comment by lamjed001** [comment]
You don't understand what you mean but you can use kj-ftp addon ( https://github.com/kleeja-official/kj-ftp )
to upload files to another server
I hope i helped you
