### ISSUE TITLE
مشكلة في تصفح المجلد الشخصي

### ISSUE THREAD

**Issue by sloom2555** [kleeja-official/kleeja#165]
المشكله هي لما اتنقل بترقيم الصفحات في الاسفل يظهر حطا مثل كذا
fileuser-1-2-3.html
طبعا مفعل html 
كذلك لم انتقل من ١ الي ٢ تمام لكن لم اضغط علي رقم ٣ يظهر خطا في التوجه وكذلك بقية الصفحات

انتظر الحل شكرا

**Comment by W3bCrak3r** [comment]
فعلا موجودة هذه المشكلة

**Comment by hanirouatbi1** [comment]
Fixed in next version
