### ISSUE TITLE
Uploading files greater as 40mb error

### ISSUE THREAD

**Issue by veritas44** [kleeja-official/kleeja#167]
Uploading files greater as 41mb /(allowed 80mb) RESULT 500 error?

**Comment by lamjed001** [comment]
Change max upload from your php config to greater than 41mb

**Comment by veritas44** [comment]
on php.ini  allowed 512mb,,on script 80mb,but error 500 show on upload

**Comment by lamjed001** [comment]
So increase max_execution_time higher than 60 ( try 300 )

**Comment by veritas44** [comment]
max_execution_time is already 300,and max_input_time 600

**Comment by veritas44** [comment]
A 500 error has occured

500 errors are generally caused by one of the following two problems.

1) A bad entry in the site .htaccess file, if you are the webmaster try logging into your cPanel, and use the file manager to rename your .htaccess file if this fixes the error you should then check the contents of the .htaccess file / roll back any recent changes.

2) A php error / code error also causes a 500 error, you can try enabling 'PHP display_errors' by following this guide Enable Display errors

If after trying both of the above solutions and you are still seeing the 500 error please do contact support
.

**Comment by veritas44** [comment]
.htaccess file renamed-error is same as before.Php ver.7.3,on php 7.4 same thing
