### ISSUE TITLE
ختم الصور في الاصدار الخير بعد اضافته مباشر من المتجر لا يظهر علي الصور

### ISSUE THREAD

**Issue by Ahmed30393** [kleeja-official/kleeja#169]
ختم الصور في الاصدار الخير بعد اضافته مباشر من المتجر لا يظهر علي الصور

**Comment by MitanOmar** [comment]
you need to make sure that it's activate in the group settings, because the plugin is checking the setting, then if the feature is active in the group setting, it's adding the watermark to the image, but if not, it's not doing any thing
