### ISSUE TITLE
Fatal error: Uncaught Error: Cannot access private property KleejaDatabase

### ISSUE THREAD

**Issue by DRIVER1ksa** [kleeja-official/kleeja#171]
![Screenshot_2020-12-24 معالج تثبيت كليجا](https://user-images.githubusercontent.com/9286120/103105132-ca3e6180-463c-11eb-832a-fd0a333deeb0.png)

**Comment by MitanOmar** [comment]
the fix of this error will ba available in the next version, thanks for reporting.
