### ISSUE TITLE
FTP Activation Problem

### ISSUE THREAD

**Issue by ramy200** [kleeja-official/kleeja#173]
FTP Activation Problem After installing the plugin, writing the required settings, and saving, when you upload a file, this error appears

Fatal error: Uncaught Error: Call to undefined function ftp_connect() in H:\root\home\ramymohi200-001\www\upload\plugins\kj_ftp\ftp.php:75 Stack trace: #0 H:\root\home\ramymohi200-001\www\upload\plugins\kj_ftp\init.php(450): kleeja_ftp->open('ftp..........', '.......', '.......', '21', '', false, false, '60') #1 H:\root\home\ramymohi200-001\www\upload\plugins\kj_ftp\ftpUploader.php(306): getKleejaFtpInstance() #2 H:\root\home\ramymohi200-001\www\upload\index.php(65): ftpUploader->upload() #3 {main} thrown in H:\root\home\ramymohi200-001\www\upload\plugins\kj_ftp\ftp.php on line 75

**Comment by MitanOmar** [comment]
make sure that the extension of the ftp for PHP is active
