### ISSUE TITLE
Instructions : Kleeja found that the File "x.json" is not safe

### ISSUE THREAD

**Issue by MadScienzzz** [kleeja-official/kleeja#175]
Can't upload a json or geojson file as kleeja thinks it's not safe

Any way to bypass this please?

Thanks.

**Comment by MitanOmar** [comment]
can you put here your website link, because i try to upload a json file, and it was working

**Comment by MitanOmar** [comment]
or open your file manager, and open the file `includes/functions.php`,
and in the end of line 601, add this code `'json'      => 'application/json',`
then if it's not work, paste your website link, and we will check it manually
