### ISSUE TITLE
مشكلة في ترقية مركز التحميل 

### ISSUE THREAD

**Issue by Sultan1989** [kleeja-official/kleeja#177]
السلام عليكم ورحمة الله 

لدي مشكلة في مركز التحميل ، هو عند الترقية تظهر لي الرسالة التالية 

`Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; SSQL has a deprecated constructor in /home/xxx/public_html/upload/includes/mysql.php on line 23

kleeja

Fatal error: Uncaught Error: Call to undefined function mysql_connect() in /home/xxx/public_html/upload/install/update.php:54 Stack trace: #0 {main} thrown in /home/xxx/public_html/upload/install/update.php on line 54`

فما الحل برأيكم ..

**Comment by MitanOmar** [comment]
make sure that the mysql extension is enabled in the cpanel
