### ISSUE TITLE
خاصية كود الأمان لا تعمل في صفحة استعادة كلمة المرور

### ISSUE THREAD

**Issue by somion** [kleeja-official/kleeja#180]
مرحبا،

أواجه مشكلة في خاصية كود الأمان في صفحة استعادة كلمة المرور، فهي لا تعمل في حال كانت ممكنة ، كما أن عملية إيقافه لا توقفه فعلياً؛ على ما يبدو أنه في حالة إيقافه يعمل داخل الصفحة دون أن يظهر، وفي كل الحالات تظهر رسالة الخطأ هذه
----
خطأ.. لم يتم إرسال كلمة المرور الجديدة!
رجوع للخلف
----

>> عند تفعيله قمت بالنقر عليه مراراً وتكراراً لتغييره وكتابة الجديد، لكن يبقى كل شيء على حاله (تظهر نفس رسالة الخطأ، ولا تصل رسالة استعادة كلمة المرور).
>> قمت باستخدام عدة متصفحات، والنتيجة نفسها.
>> قمت بمسح الكوكيز، والنتيجة نفسها.
>> الاصدار المستخدم ، 3.1.6 .

تحيتي :)

**Comment by lamjed001** [comment]
قمت من التأكد من هذا و لم اجد اي مشكل
اما اذا كنت تستعمل  cloudflare فستواجد هذا المشكل
قم بتعطيل الCaching
و اعد التجربة مرة اخرى

**Comment by somion** [comment]
لا أستخدم
cloudflare 
كما أنني أعتقد أنه في حال وجود مشكلة من هذا النوع فلن تعمل خاصية كود الأمان في كل الصفحات
لكن المشكلة تقتصر على صفحة استعادة كلمة المرور فقط!

**Comment by lamjed001** [comment]
اعطني رابط الموقع للتثبت من المشكل

**Comment by somion** [comment]
https://almayaredu.com/up/ucp.php?go=get_pass

**Comment by lamjed001** [comment]
> https://almayaredu.com/up/ucp.php?go=get_pass

ممكن تنشأ لي حساب لهذا الايميل : lamjed001@gmail.com

**Comment by somion** [comment]
> > https://almayaredu.com/up/ucp.php?go=get_pass
> 
> ممكن تنشأ لي حساب لهذا الايميل : [lamjed001@gmail.com](mailto:lamjed001@gmail.com)

تم

**Comment by lamjed001** [comment]
المشكل من function mail
شغل خاصية ارسال رسائل بريد من php

**Comment by somion** [comment]
هل تقصد على صعيد الموقع ككل؟

إن كان الأمر كذلك ، فلدي نظام ووردبريس ويمكنني استعادة كلمة المرور من خلاله وارسال البريد بكفاءة عن طريق
wp_mail()

**Comment by lamjed001** [comment]
كليجا تستعمل function mail التابعة لphp لإرسال الرسائل
أما wordpress تستعمل مكتبة خاصة لإرسال الرسائل

**Comment by somion** [comment]
إن أمكنك توفير المزيد من المساعدة فكيف يمكن تفعيلها من خلال
cPanel
؟؟

**Comment by lamjed001** [comment]
ادخل الphp.ini
و ابحث عن disable_functions اذا وجدت فيها
disable_functions = mail
فأحذف كلمة mail منها

**Comment by somion** [comment]
ليست موجودة داخل
php.ini

**Comment by somion** [comment]
> انتهى الأمر بالنسبة لي
وجدت أن الخاصية مفعلة
php mail() Function

لكنها تقتصر على البريد التابع لدومين الموقع فقط، وليس لأي مزود آخر
example@mydomain.com

شكراً جزيلاً 👍
