### ISSUE TITLE
My server only allows https and using https result in unusablle site

### ISSUE THREAD

**Issue by MasoudRahmani** [kleeja-official/kleeja#181]
**Describe the bug**
Mixed Content: The page at 'https://*/up/' was loaded over HTTPS, but requested an insecure stylesheet 'http://*/up/styles/bootstrap/css/stylesheet.css'. This request has been blocked; the content must be served over HTTPS.

My server only allows https which result in unusable site and if i don't try to use https, i get 404. this a policy enforced by admin so there is nothing that can be done.

What i need is to know how to fix this or maybe an option to enable to enforce all the link to be over https.

**Screenshots**
![mixted_s_n](https://user-images.githubusercontent.com/5321268/112959448-ad905900-9158-11eb-8934-84c8850a53d9.png)

**Server (please complete the following information):**
 - OS: ubountu 18.04 LTS MATE
 - PHP version: 7.2
 - MySQL version: 14.14
 -Browser: Chrome

**Comment by lamjed001** [comment]
Go to your database select table klj_config and change siteurl value with url start with https
![image](https://user-images.githubusercontent.com/23016064/113181465-b57bf600-9249-11eb-8b44-2d1bbd31ed53.png)

**Comment by MasoudRahmani** [comment]
Thanks! It was Solved.
