### ISSUE TITLE
مشكله امتداد webp مركز كليجا

### ISSUE THREAD

**Issue by fara7kasem** [kleeja-official/kleeja#184]
عند رفع ملف webp
تظهر رساله
تعليمات
: نظام كليجا اكتشف أن الملف "all2.webp" غير آمن ويحتوي على أكواد خبيثه .. !! 

ماهو الحل؟

**Comment by MitanOmar** [comment]
[support_webp.zip](https://github.com/kleeja-official/kleeja/files/6860856/support_webp.zip)
just install this plugin, and you will not see that message with `webp` extension.
and just a note, that this is not a full support for webp images, it's just a support to upload that kind of files to the server with out error message, and still you will see the uploaded images with type `webp` under files in the controll panel

**Comment by MitanOmar** [comment]
in the next version, there will be a full support for `webp` images in kleeja, and it's not going to be soon

**Comment by fara7kasem** [comment]
شكرا لك تم التركيب وتجربه الرفع بنجاح ولكن ك ملف وليس له صوره مصغره 
في انتظار الاصدار القادم بالتوفيق
شكرا لدعمكم
