### ISSUE TITLE
Error entering and registering

### ISSUE THREAD

**Issue by uqteam** [kleeja-official/kleeja#188]
Hello, good morning, I installed the script on my site, but when a user wants to register or the admin wants to enter the user panel, he gives an error: The security code is wrong.  The code is correct but gives an error again: The security code is incorrect
![Screenshot_20210828-121522](https://user-images.githubusercontent.com/83481054/131210674-dedb810e-c333-44fe-a9dd-5c34e35962cf.jpg)

**Comment by uqteam** [comment]
name : uqpanel
password : 1Aa2Bb3Cc4Dd
address : dl.uqpanel.ir

**Comment by MitanOmar** [comment]
wen need to have access to the server to solve this problem, please contact us in our discord server

**Comment by hanirouatbi1** [comment]
This bug has been fixed in the next version, thanks for reporting.
