### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by elzahem** [kleeja-official/kleeja#189]
When I enter the administrator’s information from a password and a user name, the site logs in, but at the same moment it returns to the login interface and the same problem with users. I did not face this problem before, but after reinstalling the script, I need help, please and thank you

**Comment by MitanOmar** [comment]
check the database, in the config table, go to the option name `siteurl` and make sure that the value http protocol is in the secure version or not, and also check if the value of option `cookies_secure` is compatible with your website or not

**Comment by elzahem** [comment]
okey brother
