### ISSUE TITLE
لا يمكن جعل الصور برابط مباشر

### ISSUE THREAD

**Issue by DRIVER1ksa** [kleeja-official/kleeja#197]
يفترض انه راوبط الصور تكون مباشرة بعد رفعها

لانه بسبب طريقة الروابط الحالية يتم طلب وتحميل الصورة في كل مرة يتم فتح نفس الصفحة ولا يتم تخزينها في المتصفح مما يؤدي لزيادة الحمل على السيرفر

**Comment by MitanOmar** [comment]
go to kleeja Dashboard -> Settings -> Upload Settings

you will see a setting `Images URLs form (No stats or protection for Direct URLs)`

change the value to `Direct`

now you can have directly the direct link of the image
