### ISSUE TITLE
 Kleeja error : [ 8192:usr.php:95 ] 

### ISSUE THREAD

**Issue by Aiapir** [kleeja-official/kleeja#204]
hi
after install  show erorr
```
[Kleeja] error :
[ 8192:usr.php:95 ]
Required parameter $expire follows optional parameter $hashed
Visit Kleeja Website for more details.
```
Server
 - OS: [Linux]
 - PHP version: [7.2]

thanks...
![Kleeja-error](https://user-images.githubusercontent.com/95540833/160433266-fdd3a1eb-3e2b-41e3-9f00-04d87106221a.jpg)

**Comment by puppypvp** [comment]
have the same issue here

**Comment by MitanOmar** [comment]
it's just because u are using PHP >=8.
Kleeja is not compatible with PHP 8 yet.
Thanks you for reporting

**Comment by Aiapir** [comment]
> it's just because u are using PHP >=8. Kleeja is not compatible with PHP 8 yet. Thanks you for reporting

hi
we use **PHP  [7.2]** 
but show error **[ 8192:usr.php:95 ]**
