### ISSUE TITLE
theme/styling issue - after install

### ISSUE THREAD

**Issue by puppypvp** [kleeja-official/kleeja#205]
the theme isnt working on the site so its all just text and hyperlinks
![image](https://user-images.githubusercontent.com/81043979/161399576-9051eecc-91e4-4e4a-a85e-0d165cc15ff4.png)

**Comment by MitanOmar** [comment]
if you can login to the admin dashboard, go to settings, and the site URL, and make it to start with `https://`.
if you can not open the dashboard, then using `phpmyadmin` open the kleeja database, and from the config table, find a row with setting name called `siteurl`, change the setting value to start with `https://`.
and i think this is the issue that you are facing it

**Comment by puppypvp** [comment]
That didn't work. Looks the same even after I edited the database
