### ISSUE TITLE
Regarding closed issue 205

### ISSUE THREAD

**Issue by puppypvp** [kleeja-official/kleeja#207]
Style/theme is still broke. Looks the same as before, just text and hyperlinks

**Comment by MitanOmar** [comment]
then i need to check your website information, could you please send me the URL of your website, and i will check it

**Comment by puppypvp** [comment]
> then i need to check your website information, could you please send me the URL of your website, and i will check it

https://upload.puppypvp.xyz

**Comment by MitanOmar** [comment]
as i told you, it's http error in the siteurl in the config table

**Comment by puppypvp** [comment]
but i edited that.

**Comment by MitanOmar** [comment]
could you please join our discord channel, and contact me there. to take the login information and update it

**Comment by puppypvp** [comment]
where is the discord?

**Comment by MitanOmar** [comment]
i think the website is working now
