### ISSUE TITLE
كود الأمان خاطيء

### ISSUE THREAD

**Issue by HESHAMAREBI** [kleeja-official/kleeja#210]
السلام عليكم ورحمة الله وبركاته

يوجد مشكلة تسجيل الدخول من أول تثبيت السكربت وتكرر دائما  كود الأمان خاطيء
http://education.net.ly/upload/ucp.php?go=login
الرجاء النظر في مشكلة 

وشاكر لكم هذا العمل الرائع

**Comment by HESHAMAREBI** [comment]
السلام عليكم
تم تعطيل كود الامان بعد اتبع التعلميات 
[](https://github.com/kleeja-official/kleeja/wiki/config.php-file)

ولكن عند تسجيل الدخول يتم الدخول ومن ثم الخروج تلقائيا من الموقع

**Comment by MitanOmar** [comment]
وعليكم السلام
حاول تعديل نطاق الموقع الى https

**Comment by hanirouatbi1** [comment]
تم إصلاح هذا الخطأ في الإصدار التالي ، شكرًا على الإبلاغ.
