### ISSUE TITLE
مشكلة  [ :There is a problem with PHP session. We can not start it.: ] 

### ISSUE THREAD

**Issue by Abu-haron** [kleeja-official/kleeja#212]
Kleeja error :

[ :There is a problem with PHP session. We can not start it.: ]

Session Error!

Visit [Kleeja](http://kleeja.net/) Website for more details.
============================
Version . has been used
php 7.4.1
php 7.4.30
php 8.0.20

**Comment by MitanOmar** [comment]
Hi @Abu-haron did you change any thing in the code, or using a plugin ?
