### ISSUE TITLE
Kleeja error :  [ 8192:mysqli.php:188 ]  Automatic conversion of false to array is deprecated

### ISSUE THREAD

**Issue by tuhmaz** [kleeja-official/kleeja#217]
Kleeja error :

[ 8192:mysqli.php:188 ]

Automatic conversion of false to array is deprecated

**Comment by hanirouatbi1** [comment]
PHP 8 not supported yet, move to PHP 7.4 and it will work fine

**Comment by tuhmaz** [comment]
> PHP 8 not supported yet, move to PHP 7.4 and it will work fine

hi hani
i have problem after the return to php 7.4 all file with .doc or .docx not download correctly please check this link https://www.alemancenter.com/up/download5390.html
i need help >>>
thanks

**Comment by hanirouatbi1** [comment]
> > PHP 8 not supported yet, move to PHP 7.4 and it will work fine
> 
> hi hani i have problem after the return to php 7.4 all file with .doc or .docx not download correctly please check this link https://www.alemancenter.com/up/download5390.html i need help >>> thanks

I checked in my side with my test domain and everything works perfectly, make sure that you didn't installed any external plugin or modified kleeja files.

**Comment by tuhmaz** [comment]
> > > PHP 8 not supported yet, move to PHP 7.4 and it will work fine
> > 
> > 
> > hi hani i have problem after the return to php 7.4 all file with .doc or .docx not download correctly please check this link https://www.alemancenter.com/up/download5390.html i need help >>> thanks
> 
> I checked in my side with my test domain and everything works perfectly, make sure that you didn't installed any external plugin or modified kleeja files.

i make sure , i dont install any external plugin or modified kleeja file.
i have 8000 file just pdf is work fine >>>

**Comment by hanirouatbi1** [comment]
> > > > PHP 8 not supported yet, move to PHP 7.4 and it will work fine
> > > 
> > > 
> > > hi hani i have problem after the return to php 7.4 all file with .doc or .docx not download correctly please check this link https://www.alemancenter.com/up/download5390.html i need help >>> thanks
> > 
> > 
> > I checked in my side with my test domain and everything works perfectly, make sure that you didn't installed any external plugin or modified kleeja files.
> 
> i make sure , i dont install any external plugin or modified kleeja file. i have 8000 file just pdf is work fine >>>

I checked your URL and it's working fine.
