### ISSUE TITLE
لدي مشكلة بتسجيل الدخول كود الأمان خاطيء

### ISSUE THREAD

**Issue by emadem55** [kleeja-official/kleeja#221]
مرحبا بالجميع
لدي مشكلة اثناء محاولة تسجيل الدخول للسكربت وهي كود الأمان خاطيء وقبلها مباشرة كان يعيد تحويلي لصفحة تسجيل الدخول تلقائياً

**Comment by hanirouatbi1** [comment]
تم اصلاح هذا المشكل في الاصدار الجديد الدي سيصدر لاحقا
لإصلاح المشكل غير محتوى ملف includes/captcha.php بهذا المحتوى
https://raw.githubusercontent.com/kleeja-official/kleeja/next-version/includes/captcha.php
