### ISSUE TITLE
Required parameter follows optional parameter error in Kleeja functions.php and usr.php files with PHP 8.0

### ISSUE THREAD

**Issue by hmdqr** [kleeja-official/kleeja#222]
When using PHP 8.0, Kleeja users may encounter a 'Required parameter follows optional parameter' error in the functions.php and usr.php files. This error occurs because the function parameters are defined in a way that is no longer supported in PHP 8.0. To fix the issue, the affected functions need to be modified to ensure that required parameters come before optional parameters. This issue should be addressed to ensure compatibility with PHP 8.0.

**Comment by hanirouatbi1** [comment]
Thanks for reporting, but we are already working on Kleeja to support PHP 8.x, and this issue has already been fixed in the [next-version branch](https://github.com/kleeja-official/kleeja/tree/next-version)
