### ISSUE TITLE
Install OK but blank page

### ISSUE THREAD

**Issue by accnetdev** [kleeja-official/kleeja#225]
Hi,
Kleeja installed at my hosting o2switch.
Install all OK, but at the end, when pointing on normal or admin URL I get a blank page with no error, just blank.
Any idea ?

**Comment by jibap** [comment]
Bonjour, 
Même chose pour moi, je suis en PHP 8.2, ce doit être la cause de l'erreur (500)... 
Tant pis, j'aurai au moins essayé !

**Comment by jibap** [comment]
it works perfectly ! Thanks a lot.

I made the french translation, are you interested to add it to the project ?
