### ISSUE TITLE
website is dameg

### ISSUE THREAD

**Issue by Binkaddas1** [kleeja-official/kleeja#228]
I have been using the Download Center for a long time with the default style of the center, and for about a week I have been facing a problem that everything on the site has changed and it has become disorganized.

![image](https://github.com/kleeja-official/kleeja/assets/143866997/cf131ece-1f4f-41b6-93e6-78b6fc19e605)

Please try to help me or if you have update for this issu

https://binkaddas.net/

**Comment by hanirouatbi1** [comment]
You're using an http:// link to a stylesheet (which you defined it in kleeja settings "Service URL")
![image](https://github.com/kleeja-official/kleeja/assets/23016064/96436a20-b621-44aa-aea7-5f595a0a7159)
on an https:// website.

Secure websites are not allowed to mix protocols. Everything has to be embedded from a secure server. Browsers will ignore/block HTTP resources on HTTPS pages (with varying degree of strictness).

So you can access you website from only HTTP, If you want to make it work on HTTPS just go to settings and update "Service URL" to be https://binkaddas.net/

and add this in you .htaccess file before kleeja rules to redirect any http request to https
```
# Redirect HTTP to HTTPS
RewriteEngine On
RewriteCond %{HTTPS} !=on
RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
```

**Comment by Binkaddas1** [comment]
Dera Hani,

Thank you for your replay, kindly advice how to add it because I try but not working.

Regards,
[htaccess.txt](https://github.com/kleeja-official/kleeja/files/12503688/htaccess.txt)

**Comment by Binkaddas1** [comment]
i will be like the below you mean
![image](https://github.com/kleeja-official/kleeja/assets/143866997/73ce68ff-8cca-4bf3-8ed5-cfd591b88be6)

**Comment by hanirouatbi1** [comment]
Upload this to your website and rename it to .htaccess
[htaccess.txt](https://github.com/kleeja-official/kleeja/files/12503713/htaccess.txt)

**Comment by Binkaddas1** [comment]
Fist of all, really thank you Hani for your kind support, it's working fine

i am using now Kleeja 3.1.6, is there any update for the version or if i need to update my version to be compatible with PHP update in the future  because really i like this script.

regards,

**Comment by hanirouatbi1** [comment]
@Binkaddas1 You are welcome
1- Yes, there will be a new update, version 3.1.7, that supports new PHP versions.
2- Kleeja is an open-source project with the potential for additional plugins. Anyone is welcome to create and contribute plugins to enhance its functionality. If you have ideas for new features, feel free to share them with us, and we'll do our best to bring them to life.

**Comment by Binkaddas1** [comment]
Sure, thank you for you support and help
