### ISSUE TITLE
ممكن تضيفون ميزة أقصى حجم للملفات التي قد رفعت لكل عضوية

### ISSUE THREAD

**Issue by khalidSA111** [kleeja-official/kleeja#231]
السلام عليكم
ممكن تضيفون ميزة أقصى حجم للملفات التي قد رفعت لكل عضوية
مثال
لنقل عضو اقصى حجم للملفات يمكن رفعه 1 غيغا = اقصى حجم للملفات اللتي رفعت 5000 الاف غيغا بعدها يجب حذف الملفات الغير مهمة وهكذا
سأتبرع لمن سيطور السكربت ويضيف هذي الميزة واعتقد انها ميزة مهمة جدا
ايميلي
devzonkm@gmail.com
شكرا

**Comment by Binkaddas1** [comment]
Is there new version of Kleeja 3.1.7 ?

**Comment by MrMahmoudos** [comment]
ممكن اتواصل معاك استاذ خالد
