### ISSUE TITLE
after move the hosting to new web host

### ISSUE THREAD

**Issue by Binkaddas1** [kleeja-official/kleeja#234]
السلام عليكم ورحمة الله وبركاته

بعد نقل الموقع من استضافة الي استضافة جديده يتم تحميل الملفات ولكن الصوره لا تظهر في الصفحه الرئيسية لمعرفة الصورة

زلكن الرابط يعمل بشكل جيد عند لصقة بالمنتديات

ارجوا التكرم بالمساعده

![issue](https://github.com/kleeja-official/kleeja/assets/143866997/e0b1a1f2-7093-4e54-9ce1-711058799891)

**Comment by RouatbiH** [comment]
هل تستخدم PHP 8؟
أذا كنت تستعمل اصدار كليجا <= 3.1.6 ينصح بإستخدام PHP 7

**Comment by RouatbiH** [comment]
كذلك تأكد من أنك مفعل إضافة GD في PHP
![Screenshot20220218100933](https://github.com/kleeja-official/kleeja/assets/23016064/0b3081ca-0041-4445-a9a8-d7d4426df02c)

**Comment by Binkaddas1** [comment]
بارك الله فيك استاذي وشكر لك نعم تم تفعيل الخاصية التي ذكرتها واشتغل المركز بالتمام

الف شكر

![Screenshot 2024-07-06 094056](https://github.com/kleeja-official/kleeja/assets/143866997/cb58db3b-e4f0-450b-8318-4a080eb2e186)
