### ISSUE TITLE
ملف غير امن واكواد خبيثة

### ISSUE THREAD

**Issue by abojamil** [kleeja-official/kleeja#83]
السلام عليكم، يعطيكم العافية

عندي اشكالية عند رفع ملف بصيغة Mkv
تظهر رسالة مفادها ان نظام كليجا اكتشف ان الملف غير امن ويحتويعلى اكواد خبيثة

مع العلم ان الصيغة غير محظورة ومسموح بها، وجربت تغيير اسم الملف بلا فائدة، وشكرا

**Comment by MitanOmar** [comment]
وعليكم السلام
في المسار التالي :
domain.com/kleeja/includes/functions.php
Line 807
اضف اليها السطر التالي 

"mkv" => "video/x-matroska" ,

**Comment by abojamil** [comment]
ظهرت رسالة جديدة
"تعليمات : لقد قمت بتخطي عدد مرات عرض الصفحة بالوقت المحدد.."

**Comment by MitanOmar** [comment]
قم بالدخول للموقع من جديد و ارفعها

**Comment by abojamil** [comment]
اشكرك، الوضع سليم الان

**Comment by MitanOmar** [comment]
العفو

**Comment by abdumu** [comment]
@MitanOmar could you add this to kleeja code. 🤸

**Comment by MitanOmar** [comment]
@abdumu  sure

**Comment by fara7kasem** [comment]
نفس المشكله عندي ولكن في امتداد webp 
ماهو الحل رجاء

**Comment by Zeinabnemati** [comment]
Uploading [v-s.mobi]solmaz kaan eskilerden video.mp4.mp4…

**Comment by mtr796** [comment]
السلام عليكم عندي مشكله برفع ملف mp3 من 10 ايام صرت احمل من موقعكم وكل شي تمام من عشر ساعات حملت ومافي شي من ساعه اريد احمل مو راضي يحمل الملف وكل الملفات اللي حملتهم كلهم توقفو بليز ابي مساعده لو سمحتم

**Comment by mtr796** [comment]
هذا اللي يطلع لي لا جيت ارفع ملف mp3 ادخل على التحديث ما يرضى احدث The requested URL was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.
